services:
  db:
    image: postgres
    container_name: cripto-postgres
    environment:
      POSTGRES_USER: cripto
      POSTGRES_PASSWORD: cripto
      POSTGRES_DB: cripto
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: